# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 03:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('excerpt', models.TextField(blank=True, max_length=200, verbose_name=b'\xe6\x91\x98\xe8\xa6\x81')),
                ('img', models.ImageField(blank=True, null=True, upload_to=b'article_img/%Y/%m/%d/', verbose_name=b'\xe6\x96\x87\xe7\xab\xa0\xe5\x9b\xbe\xe7\x89\x87')),
                ('body', models.TextField()),
                ('views', models.PositiveIntegerField(default=0, verbose_name=b'\xe9\x98\x85\xe8\xaf\xbb\xe9\x87\x8f')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xb6\xe9\x97\xb4')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_info', models.CharField(default=b'', max_length=50, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('img', models.ImageField(upload_to=b'banner/', verbose_name=b'\xe8\xbd\xae\xe6\x92\xad\xe5\x9b\xbe')),
                ('link_url', models.URLField(max_length=100, verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87\xe9\x93\xbe\xe6\x8e\xa5')),
                ('is_active', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x98\xafactive')),
            ],
            options={
                'verbose_name': '\u8f6e\u64ad\u56fe',
                'verbose_name_plural': '\u8f6e\u64ad\u56fe',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xe5\x8d\x9a\xe5\xae\xa2\xe5\x88\x86\xe7\xb1\xbb')),
                ('index', models.IntegerField(default=999, verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb\xe6\x8e\x92\xe5\xba\x8f')),
            ],
            options={
                'verbose_name': '\u535a\u5ba2\u5206\u7c7b',
                'verbose_name_plural': '\u535a\u5ba2\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name=b'\xe9\x93\xbe\xe6\x8e\xa5\xe5\x90\x8d\xe7\xa7\xb0')),
                ('linkurl', models.URLField(max_length=100, verbose_name=b'\xe7\xbd\x91\xe5\x9d\x80')),
            ],
            options={
                'verbose_name': '\u53cb\u60c5\u94fe\u63a5',
                'verbose_name_plural': '\u53cb\u60c5\u94fe\u63a5',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xe6\x96\x87\xe7\xab\xa0\xe6\xa0\x87\xe7\xad\xbe')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0\u6807\u7b7e',
                'verbose_name_plural': '\u6587\u7ae0\u6807\u7b7e',
            },
        ),
        migrations.CreateModel(
            name='Tui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xe6\x8e\xa8\xe8\x8d\x90\xe4\xbd\x8d')),
            ],
            options={
                'verbose_name': '\u63a8\u8350\u4f4d',
                'verbose_name_plural': '\u63a8\u8350\u4f4d',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Category', verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe'),
        ),
        migrations.AddField(
            model_name='article',
            name='tui',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Tui', verbose_name=b'\xe6\x8e\xa8\xe8\x8d\x90\xe4\xbd\x8d'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe4\xbd\x9c\xe8\x80\x85'),
        ),
    ]
