# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 10:22
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181113_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name=b'\xe5\x86\x85\xe5\xae\xb9'),
        ),
    ]
